### ISSUE TITLE
Todo List (crate `s3s`)

### ISSUE THREAD

**Issue by Nugine** [Nugine/s3s#82]
+ [ ] Adopt [date_time_format_test_suite](https://github.com/awslabs/smithy-rs/blob/main/rust-runtime/aws-smithy-types/test_data/date_time_format_test_suite.json)
+ [ ] Upgrade to hyper 1.0 (waiting for upstream)
+ [ ] More typed header values
