### ISSUE TITLE
Todo List (crate `s3s-aws`)

### ISSUE THREAD

**Issue by Nugine** [Nugine/s3s#84]
+ [x] S3 service as `SmithyConnector`
+ [x] S3 Client as `S3Service`
+ [x] Conversions between s3s and aws types
